version: 2.1
orbs:
  ruby: circleci/ruby@1.0 
  node: circleci/node@2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7-node
    executor: ruby/default
    steps:
      - checkout # pull down our git code.
      - ruby/install-deps # use the ruby orb to install dependencies
      # use the node orb to install our packages
      # specifying that we use `yarn` and to cache dependencies with `yarn.lock`
      # learn more: https://circleci.com/docs/2.0/caching/
      - node/install-packages: 
          pkg-manager: yarn
          cache-key: "yarn.lock"
    # steps:
    #   - checkout
    #   - run:
    #       name: Force Bundler Version
    #       command: |
    #         sudo gem update --system
    #         echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
    #         source $BASH_ENV
    #         gem install bundler 
  



  # test:
  #     docker:
  #       - image: circleci/ruby:2.6.3-stretch-node
  #     executor: ruby/default
  #     steps:
  #     - checkout
  #     - run:
  #         name: Update bundler
  #         command: gem install bundler:2.1.4
  #     - run:
  #         name: Run bundler
  #         command: bundle install
  #     - run: echo "this is the test job"
  #     - run:
  #         name: DB create
  #         command: bundle exec rails db:create db:schema:load --trace
  #     - run:
  #         name: RSpec
  #         command: |
  #           bundle exec rspec --profile 10 \
  #                             --format progress

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
